### ISSUE TITLE
Add variables to execute paste, other actions

### ISSUE THREAD

**Issue by bknickelbine** [xmichelo/Beeftext#33] opened 2018-01-19 21:53 UTC
This would be helpful to add copied data into substitutions dynamically. For example, customer names, order numbers, etc.

**Comment by xmichelo** [comment] 2018-01-21 19:38
Hi @bknickelbine, 

Thank you for your feedback. I am planning to integrate a feature named 'placeholders' (see issue #29) that seem to match your request.

Placeholders are be special instructions placed in the substitution text. For instance:

- ```#{clipboard}``` will be replaced by the content of the clipboard.
- ```#{dateTime:yyyy-mm-dd}``` will be replaced by the current date and or time using a customizable format.
- ```#{caret}``` Will indicate where the text cursor should be placed after the substitution is performed.
- ```#{combo:<comboName>}``` will be replaced by the contents of the substitution text for the combo <comboName>, provided it does not create an endless loop.

In a more distant future, I also plan a ```#{var:<VariableName>:<Display Text>}``` where a dialog would pop up at substitution time and prompt the user for the value of <VariableName>.

Will this feature suit your needs?

**Comment by bknickelbine** [comment] 2018-01-22 16:55
Yes, that would be great. I skimmed through the other issues but must have overlooked the mention of clipboard placeholder. Excited to see those new features!

**Comment by xmichelo** [comment] 2018-01-22 20:25
Perfect. A first version with ```#{clipboard}``` and #{dateTime} should be available in a week or two.

I'm closing this issue as it is a duplicate of #29.

**Closed by xmichelo** 2018-01-22 20:25 UTC
Labels: duplicate, feature request, normal priority
