### ISSUE TITLE
last letter of keyword intermittently replaces char before expanded snippet

### ISSUE THREAD

**Issue by Zoombini50** [xmichelo/Beeftext#112] opened 2018-11-28 16:38 UTC
I run into this quite a lot with just about all my combos, but here's an example.
### Expected behavior
Say I have a combo in which the keyword "pprox" expands to "approximately." Therefore, if I type "Map scale pprox 1:10,000", I should get "Map scale approximately 1:10,000".

### Actual behavior
Intermittently, the combo works as expected. I haven't yet figured out how or why. Most of the time however, I'll get "Map scalexapproximately 1:10,000", i.e. the space before "pprox" was deleted and replaced with the "x" from the end of the keyword. New lines prior to a keyword get deleted as well. I then have to go back and edit manually, which gets annoying fast. :)

### Steps to reproduce the behavior
I've had trouble *not* reproducing it, actually. It happens all the dang time just in normal use! And then sometimes it doesn't for a little while. I haven't been able to figure out why. :/

I *think* it's more likely to happen if I've deleted a character right before typing the keyword, but it can happen if I just click and type, too. Clipboard expansion can be on or off, it happens either way.

### Operating system
Windows 7 Enterprise, Service Pack 1, 32-bit and 4GB of RAM. I'm a librarian, so I usually encounter the bug in OCLC Connexion, but I've seen it happening in Notepad and Firefox as well (heck, I triggered it on purpose while writing this post!). I don't think it's application-specific.

If it makes a difference, I tend to have several programs open at a time and I use the Dvorak keyboard.

**Comment by Zoombini50** [comment] 2018-12-10 16:51
I've been using the portable version (it's my work computer). Running from the hard drive. And sure, I'm happy to beta test!

I have a bunch of combos already, so if possible I'd like to hang onto my comboList.json file between versions (i.e. copy it into the new folder or export then import), but if it becomes a possible culprit I could start fresh. :)

**Comment by Zoombini50** [comment] 2018-12-21 15:40
Interesting variation popped up today:
"vmp" expands to "ǂv Maps." Typed it in (i.e. "Local County (State) vmp") and got a field reading "Local County (State)ǂv Maps.p"
(Locations edited for privacy. :slightly_smiling_face: )
These computers are... not the newest, so the processing speed may or may not be playing into the problem. Anyhow, on rare occasion the extra char gets dropped elsewhere in the text instead of at the beginning. The character before the combo still disappears though.

**Comment by xmichelo** [comment] 2019-03-06 17:56
Hi @Zoombini50 

You may want to have a look at issue #131, that might be related to your problem. You will find some test builds with potential workaround for the problem.

**Comment by Zoombini50** [comment] 2019-03-26 13:41
Hi, sorry I haven't checked back in! Our office computers were upgraded a few weeks ago (from Windows 7 to new machines running Windows 10). Oddly enough, that cut down on the problem quite a bit for Beeftext 1.7; it's nearly vanished under 1.8. I'll download 1.9 today.

**Comment by xmichelo** [comment] 2019-03-27 04:18
Hi @Zoombini50 
If the problem is still there, you can play with the new parameter 'Delay between simulated keystrokes'. The default value is 12ms, you can increase it to see if it fixes your problem.

**Comment by xmichelo** [comment] 2019-04-13 10:29
Closing, assuming it is fixed.

**Closed by xmichelo** 2019-04-13 10:29 UTC
Labels: bug, high priority
