### ISSUE TITLE
Trigger-text is case-sensitive !!

### ISSUE THREAD

**Issue by alienfxfiend** [xmichelo/Beeftext#133] opened 2019-03-08 23:14 UTC
### Actual behavior
Why is trigger-words case-sensitive ? Please make it so it executes when triggers are either in lower-case or upper-case. Thank you.

### Operating system
Windows 10

**Comment by xmichelo** [comment] 2019-03-09 07:50
Hi. @alienfxfiend 

That's actually something I saw in other products. you can choose whether a snippet is case sensitive or not. It should not be hard to implement, and will be in a future release.

**Comment by alienfxfiend** [comment] 2019-03-23 00:01
OK thank you !

**Comment by TerDale** [comment] 2019-11-07 15:29
Indeed, would be nice to have something like this:
- combo keyword: "ent", snippet: "entraînement"
- if I key in "ent", I would expect it completed to "entraînement"
- while if I key in "Ent", I would expect it completed to "Entraînement"

Currently, one has to define 2 combos for this: for for each case.
Thanks in advance Xavier!

**Comment by xmichelo** [comment] 2019-11-10 14:05
@TerDale your suggestion will not be implemented. The reason is *performance* that the processing must be done at every keystroke, and has to be minimalist to keep the application and system smooth on as many computers as possible. case insensitive comparison is fast enough, analysing and reproducing case is not.

**Comment by TerDale** [comment] 2019-11-12 08:31
@xmichelo OK, thanks for the details. And even though, as a developer myself, it's hard to understand why case insensitive comparison would be faster than analyzing case of first letter... Indeed, in the former case analysis must be done for each & every letter of the keyword (even if provided by the used development framework) vs. a single one in the latter.

**Comment by xmichelo** [comment] 2021-07-30 05:32
Implemented in #386.

**Closed by xmichelo** 2021-07-30 05:32 UTC
Labels: feature request, low priority
