### ISSUE TITLE
After update to 1.9, specific combination doesn't work, cannot isolate issue

### ISSUE THREAD

**Issue by cortstar** [xmichelo/Beeftext#151] opened 2019-04-08 21:35 UTC
The combination worked prior to 1.9-

### Expected behavior
The clipboard item should be surrounded by the snippet:
{panel:title=#{cursor}|borderStyle=solid|borderColor=#CCC|bgColor=#c6f1ff}#{clipboard}{panel}

### Actual behavior
The snippet does not appear. The clipboard text appears, but is not surrounded by the other text in the snippet. The cursor appears at a certain point inside the text. 

Only occurs with some text. Here is an example:
`I'm following up on your question about which invoice was missed. It seems we have payments for all your invoices except INV12209, which I have attached a copy of to this e-mail.

Let me know if you have any questions, and when the payment can be made on the invoice.

Thanks so much!`
### Steps to reproduce the behavior
* Add the snippet
* Copy the provided text
* Execute the snippet with the keyword

### Operating system
Windows 10 Pro 64bit x64-architecture

**Comment by cortstar** [comment] 2019-04-08 21:36
I tried a number of things but couldn't work out why the specific combination of this snippet and certain text seems to fail. It seems to work with certain text but not others. Other snippets including my keyboard work with this text.

**Comment by xmichelo** [comment] 2019-04-10 05:04
Hi @cortstar.
I think I found what the problem is (an issue with the final positioning of the cursor). Here is a build with a potential fix. Could you please test it and let me know if it solves your issue:

- [Installer](https://1drv.ms/u/s!AjydspuvJDSnvRO8Z-ZEOUPvQfZX)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSnvRKgk8Vk5Pp0WFr_)

**Comment by xmichelo** [comment] 2019-04-14 14:36
I'm closing the issue as it is blocking the release of v1.10. @cortstar If the issue is still there, please re-open.

**Closed by xmichelo** 2019-04-14 14:36 UTC
Labels: bug, normal priority

**Comment by cortstar** [comment] 2019-04-22 14:44
Just confirming that the fix worked for me, thanks

**Comment by xmichelo** [comment] 2019-04-22 17:34
Great. Thanks you for the feedback.
