### ISSUE TITLE
Bug report ; I cant enter to beeftext in Windows 7

### ISSUE THREAD

**Issue by ghost** [xmichelo/Beeftext#270] opened 2020-06-28 15:21 UTC
### Windows 7
![10](https://user-images.githubusercontent.com/45869814/85951488-6839c380-b95b-11ea-8e7f-dc61c2af03ad.png)

**Comment by iiBaHy** [comment] 2020-06-28 15:23
I am not the only who faces this prb

**Comment by mathieucaroff** [comment] 2020-06-28 15:26
I'm on Windows 10. I don't have this problem, but here's the translation for the error in the image:

> Beeftext.exe - System error
>
> Unable to start the program because `api-ms-win-crt-runtime-l1-1-0.dll` is missing on your computer. Try to reinstall the program to correct this problem.

**Comment by iiBaHy** [comment] 2020-06-28 15:35
Reinstall beeftext? i tryed this but same

**Comment by iiBaHy** [comment] 2020-06-28 15:38
and yeah when i upgraded to windows 10, a prb has ended

**Comment by iiBaHy** [comment] 2020-06-28 15:38
but i need windows 7

**Comment by xmichelo** [comment] 2020-06-28 15:40
That's odd, because I tested the app on a VM with a fresh install of Windows 7 (with no patch at all) and it worked just fine.
Anyway, this is just a problem of missing DLL. 

@iiBaHy If you unzip the following file and put the DLL into you Beeftext folder, does it fix the problem: [api-ms-win-crt-runtime-l1-1-0.zip](https://github.com/xmichelo/Beeftext/files/4842530/api-ms-win-crt-runtime-l1-1-0.zip)


@mathieucaroff Thank you for translating. I'm French, but it's useful for any people encoutering the problem.

**Comment by iiBaHy** [comment] 2020-06-28 15:46
Another ddl file
![10](https://user-images.githubusercontent.com/45869814/85952096-f6fc0f80-b95e-11ea-9ff1-00846782f011.png)

**Comment by iiBaHy** [comment] 2020-06-28 15:53
@xmichelo **^^**

**Comment by xmichelo** [comment] 2020-06-28 16:05
OK. The problem is that I don't have the right version of the DLL file. Let's do this in a different way. Windows 7 is a product that is not supported anymore by Microsoft, but I am still committed to keep Beeftext running on that OS. However I do not want to spend to much time on it. 

First, please delete the DLL I sent you from the Beeftext folder.
Then go to this page and download and install the version of the *Universal C Runtime* that fit your version of your system:
- if you run Windows 7 32bit, select the version `All supported x86-based versions of Windows 7`.
- if you run Windows 7 64bit, select the version `All supported x64-based versions of Windows 7`.

This should fix your problem.

**Comment by iiBaHy** [comment] 2020-06-28 16:20
ok i will try this

**Comment by iiBaHy** [comment] 2020-06-28 16:20
But where is the link?

**Comment by xmichelo** [comment] 2020-06-28 16:22
Sorry: https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

**Comment by iiBaHy** [comment] 2020-06-28 16:25
![image](https://user-images.githubusercontent.com/45869814/85952895-4a249100-b964-11ea-8597-3e0ee5394d0c.png)

**Comment by iiBaHy** [comment] 2020-06-28 16:26
i am support in website and i need this apk

**Comment by xmichelo** [comment] 2020-06-28 18:08
OK. Please try this one: https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by iiBaHy** [comment] 2020-06-28 18:53
OK THX

**Comment by victorwestmann** [comment] 2021-02-05 01:01
So does it work now?

**Comment by xmichelo** [comment] 2021-02-05 11:53
I do not have Windows 7 anymore. You can test the latest version (8.1), I don't know if it will work.

**Closed by xmichelo** 2021-02-05 11:53 UTC
Labels: bug
