### ISSUE TITLE
Shift Key stays toggled on

### ISSUE THREAD

**Issue by AbsorbentWookie** [xmichelo/Beeftext#173] opened 2019-07-23 05:17 UTC
### Expected behavior
press combo and output snippet comes out, input returns to normal

### Actual behavior
Combos ending with a shift key + letter, leave the keyboard with shift key toggled.
Isolation steps:
- have to press respective shift key to un-toggle the shift key.
-if Right shift, left shift will not cause it to toggle off and caps lock does have desired effect, but using arrow keys causes text to be highlighted as through shift was being held down. 
- using caps lock to produce last input does not cause the behavior.
ie |nsP causes but |lsp does not

### Operating system
windows 10 1803 build 17134.860

**Comment by xmichelo** [comment] 2019-07-25 04:56
Hi.

Thank you for your report. This is a duplicate of #164, which should have been fixed in v3.0.
However the error may persist if Beeftext is setup not to use the clipboard for combo substitution, in which case there is not much I can do about it. Could you please provide me with the following information:

- What version of Beeftext are you using?
- In the preferences, is the `Use clipboard for combo substitution` box checked?

**Comment by AbsorbentWookie** [comment] 2019-08-29 06:54
Hi xmichelo,
sorry the response took so long
I'm running V5.0
currently issue only occurs in when `Use clipboard for combo substation` is unchecked

Also only seems to occur on particular keywords:
ie |battG causes the issue
soL does not
but |nK does not 
|DspQ causes
|peN does not

let me know if theres anything else I can provide

**Comment by xmichelo** [comment] 2019-09-04 05:51
Hi. What is happening is identified but tricky to fix. I modified the code to minimize the problem, but it still occurs from time to time.

Anyway, you NEED to check 'use clipboard for combo substitution', because the option will disappear very soon. Not using clipboard is not compatible with an upcoming feature: support for rich text.

**Closed by xmichelo** 2019-09-04 05:51 UTC
