### ISSUE TITLE
[Bug] keyword beginning with @ does not work anymore

### ISSUE THREAD

**Issue by stphntlbt** [xmichelo/Beeftext#460] opened 2022-01-13 10:35 UTC
#### Expected behavior
replace keyword with snippet

#### Actual behavior
do nothing

#### Steps to reproduce the behavior
create a new combo with any keyword beginning with a "@"
add snippet
try it
eg. keyword " @g ", snippet " @gmail.com "
replace the "@" with a dot for example, and it works.
it was working in 11.1 (just tested)

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
Beeftext v12.0

#### Operating system version (e.g Windows 10)
Windows 10

**Comment by xmichelo** [comment] 2022-01-13 18:56
Hi.
The issue is known and has already been fixed. The fix will be included in v13.0, due soon. Tests builds can be found in the comments of issue #443

**Closed by xmichelo** 2022-01-13 18:56 UTC
Labels: bug, Already Implemented

**Comment by stphntlbt** [comment] 2022-01-13 22:36
Hi,
I had searched for an existing topic, but didn't do it well.
Sorry.


Le jeu. 13 janv. 2022 à 19:56, Xavier Michelon ***@***.***> a
écrit :
