### ISSUE TITLE
Update to 2.0 offered but install does not complete

### ISSUE THREAD

**Issue by SanderGit** [xmichelo/Beeftext#158] opened 2019-05-20 14:09 UTC
### Expected behavior
Version 2.0 is installed
### Actual behavior
Reboots without confirmation, after reboot nothing is installed

### Steps to reproduce the behavior
- Start Beeftext 1.x, it offers to update to 2.0
- Then 1.x is uninstalled and the computer is rebooted without further consent (this is not very nice even though the first installer screen mentions something about a reboot)
- After reboot, the Beeftext program folder is present, with an uninstall.exe file, the rest is removed
- No install of 2.0 is starting

**Comment by xmichelo** [comment] 2019-05-20 15:14
Hi @SanderGit 

This is nasty. The installer should not reboot without a prompt. I will investigate this issue ASAP.

**Comment by tnay** [comment] 2019-05-20 20:45
Thanks for a program that is already useful and that I expect will become even more so in the future.
I also experienced an attempted restart without notification when I installed BT 2.0 on Windows 10 64bit.
I suspect it is due to the install of the VC runtime.

**Comment by xmichelo** [comment] 2019-05-20 20:55
Hi @tnay 

Indeed, the VC runtime was my guess too. I noticed earlier there is a `/norestart` option I am not using.

This cause makes the problem very difficult to reproduce. I initially though it could happen if you're computer was awaiting for a reboot (for instance because windows update is waiting for an appropriate time to perform an auto-reboot), but tests on several VMs proved me wrong.

Another option I'm considering is to ditch the vcredit approach and manually copy the 2 DLLs I need to the installation folder. This is what I already do for the Portable Edition.

**Comment by xmichelo** [comment] 2019-05-21 16:45
I decided to get rid of the Visual C++ redistributable runtime.
Fixed by 12fb305a.

**Closed by xmichelo** 2019-05-21 16:45 UTC
Labels: bug, high priority
