### ISSUE TITLE
[Feature]  - nested groups

### ISSUE THREAD

**Issue by tharindha** [xmichelo/Beeftext#508] opened 2022-08-22 06:37 UTC
**Is your feature request related to a problem? Please describe.**
Is it possible we can have nested groups supported? 
like
**Support Channels**
  ---**phone numbers**
        ---entry1
        ---entry2
        ---entry3
 ---**email addresses**
        ---email1
        ---email2
 ---**mail addresses**
        ---mail1
        ---mail2

![image](https://user-images.githubusercontent.com/66806493/185855146-4f7e505e-327e-4592-a6c6-9718acf10f42.png)

**Comment by xmichelo** [comment] 2022-08-23 05:22
Hi. Thank you for your suggestion. This has already been requested, and may be implemented one day.
Closes as a duplicate of #470.

**Closed by xmichelo** 2022-08-23 05:22 UTC
Labels: duplicate, feature request
