### ISSUE TITLE
Combo not appearing after keyword is typed

### ISSUE THREAD

**Issue by celestinie** [xmichelo/Beeftext#355] opened 2021-02-13 20:10 UTC

**Comment by xmichelo** [comment] 2021-02-14 05:29
Hi.
A few question. First of all, can you please update to the latest version (v8.1).

- Is the keyword deleted when you try to trigger the combo?
- Do you here the sound notification? (if enabled in the Preferences)
- What is the language of the system, and what keyboard layout are you using?
- If in the preferences, in the `Advanced` tab, you toggle the `Use legacy copy/paste` option, does it fix the problem?
- Do you use any clipboard enhancement tool (Ditto, Cliper, ClipboardFusion)?

**Comment by jkhamisani** [comment] 2021-02-15 09:50
Using version : 8.1 

I am trying to use the same with my email client The Bat but the combos are not working. However outside the mail client its working fine on notepad and in browser. 

Yes I am using Ditto and I tried after closing the Ditto but its not working.

Any suggestion.

**Comment by xmichelo** [comment] 2021-02-16 05:51
OK. Thanks for the reply. Unfortunately, if it happens only in an application and not in others, the problem is not Beeftext. The following can happen:

- Your application is actively preventing other applications from 'faking' input. This could be a safety measure to prevent malwares sending emails on your behalf. However, I quickly tested The Bat!'s trial version and did not experience your issue.
- You may have an antivirus/web protection solution that is blocking Beeftext from operating in 'sensitive application'(mail clients, web browsers, etc...).

**Closed by xmichelo** 2021-02-16 05:51 UTC
Labels: bug, normal priority
