### ISSUE TITLE
 Lower case / upper case problem

### ISSUE THREAD

**Issue by kenanunkesti** [xmichelo/Beeftext#434] opened 2021-11-06 18:38 UTC
Why did you close the matter immediately?
Have you solved the problem?

![image](https://user-images.githubusercontent.com/65110421/140620331-8adb38b8-d13a-4e92-b7a3-2433873c60a8.png)
![Animation](https://user-images.githubusercontent.com/65110421/140620351-20949b69-65b9-48d5-8723-ae6b7b722ddd.gif)

**Comment by xmichelo** [comment] 2021-11-08 05:49
Closed as duplicate of #433

**Closed by xmichelo** 2021-11-08 05:49 UTC
Labels: bug
