### ISSUE TITLE
Relaunching application should open existing running application.

### ISSUE THREAD

**Issue by AbhishekTripathi** [xmichelo/Beeftext#135] opened 2019-03-13 10:30 UTC
### Expected behavior
I use keyboard based ([keypirinha](http://keypirinha.com/)) launcher to run applications. Sometimes I quickly want to update my snippet or keyword. I relaunch the app from keypirinha but instead of showing the current application, it says that an instance of the application is already running. This is annoying. I should be able to launch the existing running application without engaging with my mouse.
### Actual behavior
Shows message that the application is already running

**Comment by AbhishekTripathi** [comment] 2019-03-13 10:54
Duplicate of #128 
Please mark it as duplicate. I would like to keep this information because the #128 talks about this problem in a different situation.

**Comment by xmichelo** [comment] 2019-03-13 17:14
Marked as a duplicate of #128. Thank you for reporting.

**Closed by xmichelo** 2019-03-13 17:14 UTC
Labels: duplicate
