### ISSUE TITLE
[Feature] centralised texts

### ISSUE THREAD

**Issue by SyncMasta** [xmichelo/Beeftext#327] opened 2020-11-25 10:24 UTC
Hello,

it would be very nice if you could store building blocks cetraly and open and use them by several people at the same time. 

Alternatively, maybe set up an auto-reimport when starting the application. 

It is very good if you use the software in a company or department and everybody should use the identical texts.

**Comment by xmichelo** [comment] 2020-11-28 14:35
I've been add plan for sharing/sync. That a rather large project and unfortunately I no not have as much time for Beeftext as a would like to at the moment.

But it will be coming to a future version.

**Comment by xmichelo** [comment] 2020-12-01 06:02
Closing as a duplicate of #157.

**Closed by xmichelo** 2020-12-01 06:02 UTC
Labels: duplicate, feature request
