### ISSUE TITLE
Semicolon key in Greek produces unwanted output

### ISSUE THREAD

**Issue by acicovic** [xmichelo/Beeftext#107] opened 2018-09-09 08:39 UTC
Hi there, and thank you for your work.

In Greek, the semicolon key (the key next to L in a QWERTY keyboard) is used to put accents. Pressing the semicolon key and then a letter will produce an accented letter (for example έ instead of ε).

### Expected behavior
Pressing semicolon key in Greek keyboard layout should produce no output and put an accent on the next letter that will be pressed.

### Actual behavior
Pressing semicolon key results in ΄΄ output.

### Steps to reproduce the behavior
Install Greek keyboard layout in OS
Run Beeftext
Switch to Greek
Press semicolon key

### Operating system
Windows 10 64 bit

I can help you test this out if needed.
Thanks!

**Comment by marcocevoli** [comment] 2019-01-04 10:54
I have exactly the same issue with a keyboard with Spanish layout: when you try to input an accented letter, such as á í ó, the accent keys output ´´ or `` , so that you can't use Beeftext together with a Spanish keyboard layout. I'm using Win 10 64 bit latest update.

**Comment by intreeking** [comment] 2019-10-03 08:49
Hello, I love Beeftext but this bug is indeed annoying. The time I save using combos is spent on fixing accent errors and pausing BT, This is just to confirm the bug whenever an accent or caron is typed using accent + letter method to write an extended character. Definitely the case for Czech and Slovak. Running BT portable 4.0 on win 10 64. Example: ´´Uplně vs. Úplně; ˇˇCesko vs. Česko. Or is there a workaround? Many thanks.

**Comment by acicovic** [comment] 2019-10-03 08:58
Personally I didn't use BT because of this because it was too cumbersome. But I'm still keeping an eye on this in case it gets fixed.

**Comment by xmichelo** [comment] 2019-10-07 18:49
I'm really sorry for this bug that has been driving me mad for ages. 
I will work on it again once I'm done with the next big release.

**Comment by intreeking** [comment] 2019-10-15 08:43
Yeas please, I am about to release a digital course, where I hope to recommend Beeftext to translators worldwide as a high value productivity tool. These people use a lot of extended characters every day. Many thanks for changing the priority. Hopefully you will find the cause of this funny behaviour soon. Any updates appreciated.

**Comment by intreeking** [comment] 2019-10-23 13:10
A similar bug reported and fixed for espanso tool:
https://github.com/federico-terzi/espanso/commit/5f71d0ad2483dfb366aff4a069246fd95b1a7793

**Comment by xmichelo** [comment] 2019-10-23 15:52
Nice finding. According to the documentation, this fix will only work for Windows 10 (version >= 1607), but it's already a big step forward if it works. I'll test ASAP, if it work on my computer (US Int'l layout), I will post a test build.

**Comment by xmichelo** [comment] 2019-10-24 05:29
Hi.

I implemented the change and it seems to work on my test VMs. I also found what seem to be a workaround for Windows version below 10.

Here are some test builds:

- [Installer](https://1drv.ms/u/s!AjydspuvJDSngZdwlV4qxgdX-RsuOg?e=ab0TIR)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngZdxPlpQiJW7GsSylw?e=MEbKTE)

Please let me know if it fixes the issue for you.

**Comment by intreeking** [comment] 2019-10-24 09:01
Hi xmichelo,
I have tested it on the portable build on Win10 64 with Czech language pack and input and it is working fine.
I have also successfully tested it on Win 7 SP1 32 with Czech language pack and keyboard.
So that's great. Thanks and best wishes!
-intreeking
@acicovic Can you test on Greek?

**Comment by acicovic** [comment] 2019-10-24 17:20
I will surely test, but that might be on Monday or Tuesday. Though if it works for Czech I don't see a reason why it shouldn't work for Greek. Will test Greek/French.

**Comment by xmichelo** [comment] 2019-10-25 04:52
Thanks for the feedback. If it turns out the bug is finally fixed, the fix will be integrated in v6.0.

**Comment by acicovic** [comment] 2019-10-30 07:12
@xmichelo On my first try after adding a combo, Avast detected the build you posted as being infected with IDP generic. This is obviously a false positive so keep it in mind when you release.

The build works correctly for me using Windows 10 1903, with Greek (Greek keyboard layout) and French (US international keyboard layout).

**Comment by xmichelo** [comment] 2019-10-30 08:20
@acicovic @intreeking Thank you for your feedback. You have no idea how much of a pain in the a** this issue have been ;). I'm glad it's fixed.

@acicovic I'm done fighting with antiviruses. The core problem is that Beeftext has to listen to keystrokes, just like malicious keyloggers do. So once in a while, heuristic engines of AV flag Beeftext as a malware.

**Closed by xmichelo** 2019-10-30 08:20 UTC
Labels: bug, high priority
