### ISSUE TITLE
Not replacing text in Chrome's address bar

### ISSUE THREAD

**Issue by viktorix** [xmichelo/Beeftext#63] opened 2018-04-09 21:05 UTC
### Expected behavior
When typing in keyword text is expanded inside Chrome's address bar.

### Actual behavior
Nothing happens.

### Steps to reproduce the behavior
Try typing in a keyword in Chrome's address bar.

### Operating system
Windows 10

I've tested this in the latest stable version of Chrome and in Canary version.

**Comment by xmichelo** [comment] 2018-04-11 16:38
Hi @viktorix 

Unfortunately, I cannot reproduce the problem, Beeftext works fine  in the address bar of the latest stable Chrome release on my system (Windows 10 Pro 64bit EN).

Here are a few things that could help:

- Run a malware scan to ensure no malicious keylogger is interfering. ([MalwareBytes](https://www.malwarebytes.com/) is a good one if you do not have a favorite).
- Try with all Chrome extensions disabled.
- Try with the option "Use clipboard for combo substitution" turned off. I recommend turning it back on when you're done testing, as the clipboard approach is performing better).
- If you can, I would be interested in a sample combo that does not work (simply export a single combo in Beeftext and attach it to the issue). That would be helpful to see if the error is linked to the actual keyword or snippet text.

Also, I'm interested in the following details about the behavior:

- If the "Play sound on combo" option is turned on, do you hear the sound when typing the keyword?
- Does the keyword disappear or does it remain visible?

**Comment by viktorix** [comment] 2018-04-12 06:07
- I'm using Sophos anti-virus and firewall, I doubt I have keylogger.
- I tried this in incognito mode in Chrome, same thing.
- It doesn't help turning this option off.
- I created simple test combo, json below. Also, please see this quick video (no audio) of the issue:
https://www.useloom.com/share/38721b67c80347d19ddbfd4dd3c3d8e3

There is no sound and keyword remains. Also, I tested this in Edge's address bar and it does work. It does not work in Firefox. Same thing as Chrome, nothing happens. In Firefox, like in Chrome, I get Google search recommendations when I type in a keyword. Maybe that's interfering with text replacement somehow?

```{
    "combos": [
        {
            "creationDateTime": "2018-04-12T01:51:16.580",
            "enabled": true,
            "keyword": "testit",
            "modificationDateTime": "2018-04-12T01:51:31.546",
            "name": "test",
            "snippet": "this is a test",
            "uuid": "{8e839a24-766b-4c8f-b2b0-e63e89e78a6f}"
        }
    ],
    "fileFormatVersion": 3,
    "groups": [
    ]
}
```

All this applies to #64 too.

**Comment by xmichelo** [comment] 2018-04-12 11:47
Hi @viktorix 

Thanks for the video and the snippet. It's still working fine for me. As the problem tends to occur in browsers only, I think the problem could be caused by your antivirus. I'm not familiar with Sophos, but I see they do have a web protection module. I guess it could be actively preventing other applications to interfere with the text field in the browser (reading text fields, replacing address bar content...)

If you have administrative rights on your computer, you could try disabling Sophos to see if the problem persists.

**Comment by smaragdus** [comment] 2018-04-18 09:38
I tested Beeftext with 3 Chromium-based browsers- [Cent Browser](https://www.centbrowser.com/), [SRWare Iron](http://www.srware.net/en/software_srware_iron.php) and [Vivaldi](https://vivaldi.com/)- Beeftext worked fine with all of them.

**Comment by viktorix** [comment] 2018-04-19 11:47
It looks like it is Sophos that's blocking text replacement. It has a feature for Safe Online Banking that provides protection from keyloggers. Turning it off, allows Beeftext to replace text in the browser address bar and file explorer.

![678ce8b7-6566-4e5d-9521-97346252a272](https://user-images.githubusercontent.com/1692600/38989707-cabbc0c2-43a5-11e8-8b64-e7cd66bbafb6.png)

**Comment by xmichelo** [comment] 2018-04-19 11:51
I'm glad you found the solution, thank you for sharing. (I'm also relieved that the problem does not come from Beeftext.) I'm closing both issues.

**Closed by xmichelo** 2018-04-19 11:51 UTC
Labels: bug
