### ISSUE TITLE
Feature request: HTML in snippets

### ISSUE THREAD

**Issue by CypherDragon** [xmichelo/Beeftext#125] opened 2019-02-21 23:48 UTC
I'd like to ask for the addition of HTML-parsed snippets. I use several snippets with URLs in them, and it would be a lot "prettier" to use an HTML-formatted snippet to include the link in an href tag, rather than the plaintext URL.

**Comment by xmichelo** [comment] 2019-02-22 07:28
Hi @CypherDragon 

Text formatting will come to Beeftext in the next big release. It will not be HTML, but [RTF](https://en.wikipedia.org/wiki/Rich_Text_Format), but in the in you will be able to modify font characteristic, change colors, add hyperlinks, etc...

**Comment by xmichelo** [comment] 2019-02-22 07:30
Duplicate of #126

**Closed** 2019-02-22 07:30 UTC
Labels: feature request
